-ifndef(NOVA_AUTH_HRL).
-define(NOVA_AUTH_HRL, true).

-define(NOVA_AUTH_DEFAULT_SESSION_VALIDITY_DAYS, 14).
-define(NOVA_AUTH_DEFAULT_ACCESS_VALIDITY_MINUTES, 60).
-define(NOVA_AUTH_DEFAULT_REFRESH_VALIDITY_DAYS, 30).
-define(NOVA_AUTH_DEFAULT_TOKEN_BYTES, 32).

-endif.
