-ifndef(NOVA_AUTH_HRL).
-define(NOVA_AUTH_HRL, true).

-define(NOVA_AUTH_DEFAULT_SESSION_VALIDITY_DAYS, 14).
-define(NOVA_AUTH_DEFAULT_TOKEN_BYTES, 32).
-define(NOVA_AUTH_DEFAULT_CONFIRM_VALIDITY_DAYS, 3).
-define(NOVA_AUTH_DEFAULT_RESET_VALIDITY_HOURS, 1).
-define(NOVA_AUTH_DEFAULT_IDENTITY_FIELD, email).
-define(NOVA_AUTH_DEFAULT_PASSWORD_FIELD, hashed_password).

-endif.
